import { Inter } from 'next/font/google'
import './globals.css'
import ReactQueryProvide from '@/providers/reactQueryProvide'
import NextAuthProvider from '@/providers/nextAuthProvider'
import AddTodo from '@/components/dialog/addTodo'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvide>
          <NextAuthProvider>
            <AddTodo/>
            {children}
          </NextAuthProvider>
        </ReactQueryProvide>  
        
      </body>
    </html>
  )
}
